-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrix_mult is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    a_ce0 : OUT STD_LOGIC;
    a_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    a_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    a_ce1 : OUT STD_LOGIC;
    a_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    b_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    b_ce1 : OUT STD_LOGIC;
    b_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    prod_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    prod_ce0 : OUT STD_LOGIC;
    prod_we0 : OUT STD_LOGIC;
    prod_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of matrix_mult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.343063,HLS_SYN_LAT=2058,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=428,HLS_SYN_LUT=1074,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv7_30 : STD_LOGIC_VECTOR (6 downto 0) := "0110000";
    constant ap_const_lv7_50 : STD_LOGIC_VECTOR (6 downto 0) := "1010000";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv8_70 : STD_LOGIC_VECTOR (7 downto 0) := "01110000";
    constant ap_const_lv8_90 : STD_LOGIC_VECTOR (7 downto 0) := "10010000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv8_B0 : STD_LOGIC_VECTOR (7 downto 0) := "10110000";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal icmp_ln10_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage7 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal icmp_ln124_reg_413 : STD_LOGIC_VECTOR (0 downto 0);
    signal reg_424 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal reg_428 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal reg_432 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal reg_437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal reg_441 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_446 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal reg_451 : STD_LOGIC_VECTOR (7 downto 0);
    signal reg_456 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln10_fu_478_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln10_reg_1316 : STD_LOGIC_VECTOR (4 downto 0);
    signal bit_sel_reg_1331 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln16_fu_499_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln16_reg_1336 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_520_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_1341 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_524_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_1359 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln16_48_fu_550_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln16_48_reg_1374 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln16_17_fu_564_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln16_17_reg_1384 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln16_47_fu_604_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln16_47_reg_1404 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_21_fu_629_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_21_reg_1419 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_21_reg_1419_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_7_reg_1444 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_9_reg_1449 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal a_load_9_reg_1464 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_11_reg_1469 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln16_49_fu_700_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln16_49_reg_1474 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_cast_fu_703_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_16_cast_reg_1479 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_17_cast_fu_715_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_17_cast_reg_1490 : STD_LOGIC_VECTOR (6 downto 0);
    signal b_load_11_reg_1500 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_13_reg_1505 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_13_reg_1525 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_15_reg_1530 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_8_reg_1580 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_10_reg_1620 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_12_reg_1625 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln12_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln12_reg_1630 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_1635 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln10_reg_1635_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal a_load_10_reg_1654 : STD_LOGIC_VECTOR (7 downto 0);
    signal b_load_14_reg_1674 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1227_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_1_reg_1679 : STD_LOGIC_VECTOR (16 downto 0);
    signal a_load_12_reg_1689 : STD_LOGIC_VECTOR (7 downto 0);
    signal a_load_14_reg_1694 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1235_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_3_reg_1709 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_2_fu_1060_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln16_2_reg_1729 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln16_6_fu_1108_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln16_6_reg_1749 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1261_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_7_reg_1769 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_9_fu_1159_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln16_9_reg_1779 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_1278_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_10_reg_1789 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln16_13_fu_1200_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln16_13_reg_1794 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_phi_mux_icmp_ln124_phi_fu_416_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln12_fu_486_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_cast_fu_532_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal tmp_3_cast_fu_545_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_52_fu_559_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_54_fu_570_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_5_cast_fu_587_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal tmp_7_cast_fu_599_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_56_fu_613_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_58_fu_624_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_9_cast_fu_641_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal tmp_11_cast_fu_653_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_60_fu_663_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_62_fu_671_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_13_cast_fu_683_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal tmp_15_cast_fu_695_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_51_fu_710_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_53_fu_723_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_cast_fu_735_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal tmp_2_cast_fu_747_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_55_fu_759_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_57_fu_771_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_4_cast_fu_787_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal tmp_6_cast_fu_799_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_59_fu_815_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_61_fu_823_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_8_cast_fu_842_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal tmp_10_cast_fu_854_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_50_fu_872_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_63_fu_880_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_12_cast_fu_943_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_14_cast_fu_955_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_64_fu_984_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln16_65_fu_1206_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal indvar_flatten1_fu_114 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln10_1_fu_908_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i2_fu_118 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal i_fu_512_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal j3_fu_122 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal j_fu_903_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_j3_load : STD_LOGIC_VECTOR (4 downto 0);
    signal b_ce1_local : STD_LOGIC;
    signal b_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal b_ce0_local : STD_LOGIC;
    signal b_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal a_ce1_local : STD_LOGIC;
    signal a_address1_local : STD_LOGIC_VECTOR (7 downto 0);
    signal a_ce0_local : STD_LOGIC;
    signal a_address0_local : STD_LOGIC_VECTOR (7 downto 0);
    signal prod_we0_local : STD_LOGIC;
    signal zext_ln16_46_fu_1222_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal prod_ce0_local : STD_LOGIC;
    signal add_ln10_fu_506_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_3_fu_537_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_16_fu_553_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_5_fu_580_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_7_fu_592_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_18_fu_607_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_19_fu_618_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_634_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_10_fu_646_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_20_fu_658_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln16_2_fu_668_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_12_fu_676_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_688_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_728_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_740_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln16_fu_756_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_19_cast_fu_764_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_780_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_792_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_cast_fu_808_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln16_1_fu_820_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_8_fu_835_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_847_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln16_15_fu_867_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln16_3_fu_877_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_2_fu_893_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_2_fu_893_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_2_fu_893_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_11_fu_936_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_948_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln16_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln16_s_fu_973_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln16_4_fu_980_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_4_fu_993_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_4_fu_993_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_4_fu_993_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_1_fu_1017_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_1_fu_1017_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_1_fu_1017_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_6_fu_1041_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_6_fu_1041_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_6_fu_1041_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1243_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln16_33_fu_1057_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_32_fu_1054_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln16_8_fu_1076_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_8_fu_1076_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_8_fu_1076_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1252_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln16_36_fu_1095_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_35_fu_1092_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln16_5_fu_1098_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_37_fu_1104_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln16_34_fu_1089_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln16_10_fu_1123_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_10_fu_1123_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_10_fu_1123_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_12_fu_1143_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_12_fu_1143_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_12_fu_1143_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1269_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln16_40_fu_1156_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_39_fu_1153_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal mul_ln16_14_fu_1171_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_14_fu_1171_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln16_14_fu_1171_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1286_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln16_43_fu_1187_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_42_fu_1184_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln16_12_fu_1190_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln16_44_fu_1196_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln16_41_fu_1181_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln16_45_fu_1213_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln16_38_fu_1210_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln16_14_fu_1216_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal grp_fu_1227_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1227_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1227_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1235_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1235_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1235_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1243_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1243_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1243_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1252_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1252_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1252_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1261_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1261_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1261_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1269_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1269_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1269_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1278_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1278_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1278_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1286_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1286_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1286_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter2_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp0_1to2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_1227_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1227_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1227_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1235_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1235_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1235_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1243_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1243_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1243_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1252_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1252_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1252_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1261_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1261_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1261_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1269_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1269_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1269_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1278_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1278_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1278_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_1286_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1286_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_1286_p20 : STD_LOGIC_VECTOR (16 downto 0);
    signal mul_ln16_10_fu_1123_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_10_fu_1123_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_12_fu_1143_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_12_fu_1143_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_14_fu_1171_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_14_fu_1171_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_1_fu_1017_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_1_fu_1017_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_2_fu_893_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_2_fu_893_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_4_fu_993_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_4_fu_993_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_6_fu_1041_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_6_fu_1041_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_8_fu_1076_p00 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln16_8_fu_1076_p10 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_condition_1225 : BOOLEAN;
    signal ap_condition_1237 : BOOLEAN;
    signal ap_condition_1242 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component matrix_mult_mul_8ns_8ns_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component matrix_mult_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    mul_8ns_8ns_16_1_1_U1 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_2_fu_893_p0,
        din1 => mul_ln16_2_fu_893_p1,
        dout => mul_ln16_2_fu_893_p2);

    mul_8ns_8ns_16_1_1_U2 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_4_fu_993_p0,
        din1 => mul_ln16_4_fu_993_p1,
        dout => mul_ln16_4_fu_993_p2);

    mul_8ns_8ns_16_1_1_U3 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_1_fu_1017_p0,
        din1 => mul_ln16_1_fu_1017_p1,
        dout => mul_ln16_1_fu_1017_p2);

    mul_8ns_8ns_16_1_1_U4 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_6_fu_1041_p0,
        din1 => mul_ln16_6_fu_1041_p1,
        dout => mul_ln16_6_fu_1041_p2);

    mul_8ns_8ns_16_1_1_U5 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_8_fu_1076_p0,
        din1 => mul_ln16_8_fu_1076_p1,
        dout => mul_ln16_8_fu_1076_p2);

    mul_8ns_8ns_16_1_1_U6 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_10_fu_1123_p0,
        din1 => mul_ln16_10_fu_1123_p1,
        dout => mul_ln16_10_fu_1123_p2);

    mul_8ns_8ns_16_1_1_U7 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_12_fu_1143_p0,
        din1 => mul_ln16_12_fu_1143_p1,
        dout => mul_ln16_12_fu_1143_p2);

    mul_8ns_8ns_16_1_1_U8 : component matrix_mult_mul_8ns_8ns_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        dout_WIDTH => 16)
    port map (
        din0 => mul_ln16_14_fu_1171_p0,
        din1 => mul_ln16_14_fu_1171_p1,
        dout => mul_ln16_14_fu_1171_p2);

    mac_muladd_8ns_8ns_16ns_17_4_1_U9 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1227_p0,
        din1 => grp_fu_1227_p1,
        din2 => grp_fu_1227_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1227_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U10 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1235_p0,
        din1 => grp_fu_1235_p1,
        din2 => grp_fu_1235_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1235_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U11 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1243_p0,
        din1 => grp_fu_1243_p1,
        din2 => grp_fu_1243_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1243_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U12 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1252_p0,
        din1 => grp_fu_1252_p1,
        din2 => grp_fu_1252_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1252_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U13 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1261_p0,
        din1 => grp_fu_1261_p1,
        din2 => grp_fu_1261_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1261_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U14 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1269_p0,
        din1 => grp_fu_1269_p1,
        din2 => grp_fu_1269_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1269_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U15 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1278_p0,
        din1 => grp_fu_1278_p1,
        din2 => grp_fu_1278_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1278_p3);

    mac_muladd_8ns_8ns_16ns_17_4_1_U16 : component matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 17)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_1286_p0,
        din1 => grp_fu_1286_p1,
        din2 => grp_fu_1286_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_1286_p3);

    flow_control_loop_pipe_U : component matrix_mult_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage7,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_const_logic_1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0)) or ((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0) and (ap_idle_pp0_0to1 = ap_const_logic_1)))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    i2_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_1237)) then 
                    i2_fu_118 <= ap_const_lv5_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    i2_fu_118 <= i_fu_512_p3;
                end if;
            end if; 
        end if;
    end process;

    icmp_ln124_reg_413_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_1242)) then 
                    icmp_ln124_reg_413 <= icmp_ln12_reg_1630;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    icmp_ln124_reg_413 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten1_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_1237)) then 
                    indvar_flatten1_fu_114 <= ap_const_lv8_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    indvar_flatten1_fu_114 <= add_ln10_1_fu_908_p2;
                end if;
            end if; 
        end if;
    end process;

    j3_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if ((ap_const_boolean_1 = ap_condition_1237)) then 
                    j3_fu_122 <= ap_const_lv5_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    j3_fu_122 <= j_fu_903_p2;
                end if;
            end if; 
        end if;
    end process;

    reg_432_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                    reg_432 <= a_q1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    reg_432 <= a_q0;
                end if;
            end if; 
        end if;
    end process;

    reg_441_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                    reg_441 <= b_q1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                    reg_441 <= b_q0;
                end if;
            end if; 
        end if;
    end process;

    reg_446_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)))) then 
                reg_446 <= a_q0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                reg_446 <= a_q1;
            end if; 
        end if;
    end process;

    reg_451_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                reg_451 <= a_q1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                reg_451 <= a_q0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                a_load_10_reg_1654 <= a_q0;
                add_ln16_1_reg_1679 <= grp_fu_1227_p3;
                b_load_14_reg_1674 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                a_load_11_reg_1469 <= a_q0;
                a_load_9_reg_1464 <= a_q1;
                b_load_11_reg_1500 <= b_q1;
                b_load_13_reg_1505 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                a_load_12_reg_1689 <= a_q1;
                a_load_14_reg_1694 <= a_q0;
                add_ln16_3_reg_1709 <= grp_fu_1235_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                a_load_13_reg_1525 <= a_q1;
                a_load_15_reg_1530 <= a_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                add_ln16_10_reg_1789 <= grp_fu_1278_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                add_ln16_13_reg_1794 <= add_ln16_13_fu_1200_p2;
                icmp_ln10_reg_1635 <= icmp_ln10_fu_920_p2;
                icmp_ln10_reg_1635_pp0_iter1_reg <= icmp_ln10_reg_1635;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln16_17_reg_1384 <= add_ln16_17_fu_564_p2;
                empty_reg_1341 <= empty_fu_520_p1;
                    tmp_reg_1359(7 downto 4) <= tmp_fu_524_p3(7 downto 4);
                    zext_ln16_48_reg_1374(4 downto 0) <= zext_ln16_48_fu_550_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                add_ln16_21_reg_1419 <= add_ln16_21_fu_629_p2;
                add_ln16_21_reg_1419_pp0_iter1_reg <= add_ln16_21_reg_1419;
                add_ln16_2_reg_1729 <= add_ln16_2_fu_1060_p2;
                    zext_ln16_47_reg_1404(4 downto 0) <= zext_ln16_47_fu_604_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                add_ln16_6_reg_1749 <= add_ln16_6_fu_1108_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                add_ln16_7_reg_1769 <= grp_fu_1261_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                add_ln16_9_reg_1779 <= add_ln16_9_fu_1159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                b_load_10_reg_1620 <= b_q1;
                b_load_12_reg_1625 <= b_q0;
                icmp_ln12_reg_1630 <= icmp_ln12_fu_914_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                b_load_7_reg_1444 <= b_q1;
                b_load_9_reg_1449 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                b_load_8_reg_1580 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bit_sel_reg_1331 <= select_ln10_fu_478_p3(4 downto 4);
                select_ln10_reg_1316 <= select_ln10_fu_478_p3;
                trunc_ln16_reg_1336 <= trunc_ln16_fu_499_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                reg_424 <= b_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then
                reg_428 <= a_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then
                reg_437 <= b_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)))) then
                reg_456 <= b_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                    tmp_16_cast_reg_1479(4 downto 0) <= tmp_16_cast_fu_703_p3(4 downto 0);
                    tmp_17_cast_reg_1490(4 downto 0) <= tmp_17_cast_fu_715_p3(4 downto 0);
                    zext_ln16_49_reg_1474(4 downto 0) <= zext_ln16_49_fu_700_p1(4 downto 0);
            end if;
        end if;
    end process;
    tmp_reg_1359(3 downto 0) <= "0000";
    zext_ln16_48_reg_1374(6 downto 5) <= "00";
    zext_ln16_47_reg_1404(7 downto 5) <= "000";
    zext_ln16_49_reg_1474(5) <= '0';
    tmp_16_cast_reg_1479(5) <= '1';
    tmp_17_cast_reg_1490(6 downto 5) <= "10";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage7_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter2_stage0, ap_idle_pp0_0to1, ap_idle_pp0_1to2, ap_block_pp0_stage1_subdone, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_const_logic_1 = ap_condition_exit_pp0_iter2_stage0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to2 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    a_address0 <= a_address0_local;

    a_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0, ap_block_pp0_stage1, tmp_3_cast_fu_545_p1, ap_block_pp0_stage2, tmp_7_cast_fu_599_p1, ap_block_pp0_stage3, tmp_11_cast_fu_653_p1, ap_block_pp0_stage4, tmp_15_cast_fu_695_p1, ap_block_pp0_stage5, tmp_2_cast_fu_747_p1, ap_block_pp0_stage6, tmp_6_cast_fu_799_p1, ap_block_pp0_stage7, tmp_10_cast_fu_854_p1, tmp_14_cast_fu_955_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_address0_local <= tmp_14_cast_fu_955_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            a_address0_local <= tmp_10_cast_fu_854_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            a_address0_local <= tmp_6_cast_fu_799_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            a_address0_local <= tmp_2_cast_fu_747_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            a_address0_local <= tmp_15_cast_fu_695_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            a_address0_local <= tmp_11_cast_fu_653_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            a_address0_local <= tmp_7_cast_fu_599_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_address0_local <= tmp_3_cast_fu_545_p1(8 - 1 downto 0);
        else 
            a_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    a_address1 <= a_address1_local;

    a_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0, tmp_cast_fu_532_p1, ap_block_pp0_stage1, tmp_5_cast_fu_587_p1, ap_block_pp0_stage2, tmp_9_cast_fu_641_p1, ap_block_pp0_stage3, tmp_13_cast_fu_683_p1, ap_block_pp0_stage4, tmp_1_cast_fu_735_p1, ap_block_pp0_stage5, tmp_4_cast_fu_787_p1, ap_block_pp0_stage6, tmp_8_cast_fu_842_p1, ap_block_pp0_stage7, tmp_12_cast_fu_943_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            a_address1_local <= tmp_12_cast_fu_943_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            a_address1_local <= tmp_8_cast_fu_842_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            a_address1_local <= tmp_4_cast_fu_787_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            a_address1_local <= tmp_1_cast_fu_735_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            a_address1_local <= tmp_13_cast_fu_683_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            a_address1_local <= tmp_9_cast_fu_641_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            a_address1_local <= tmp_5_cast_fu_587_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            a_address1_local <= tmp_cast_fu_532_p1(8 - 1 downto 0);
        else 
            a_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    a_ce0 <= a_ce0_local;

    a_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage7_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            a_ce0_local <= ap_const_logic_1;
        else 
            a_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    a_ce1 <= a_ce1_local;

    a_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage7_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            a_ce1_local <= ap_const_logic_1;
        else 
            a_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln10_1_fu_908_p2 <= std_logic_vector(unsigned(indvar_flatten1_fu_114) + unsigned(ap_const_lv8_1));
    add_ln10_fu_506_p2 <= std_logic_vector(unsigned(i2_fu_118) + unsigned(ap_const_lv5_1));
    add_ln16_12_fu_1190_p2 <= std_logic_vector(unsigned(zext_ln16_43_fu_1187_p1) + unsigned(zext_ln16_42_fu_1184_p1));
    add_ln16_13_fu_1200_p2 <= std_logic_vector(unsigned(zext_ln16_44_fu_1196_p1) + unsigned(zext_ln16_41_fu_1181_p1));
    add_ln16_14_fu_1216_p2 <= std_logic_vector(unsigned(zext_ln16_45_fu_1213_p1) + unsigned(zext_ln16_38_fu_1210_p1));
    add_ln16_15_fu_867_p2 <= std_logic_vector(unsigned(zext_ln16_49_reg_1474) + unsigned(ap_const_lv6_10));
    add_ln16_16_fu_553_p2 <= std_logic_vector(unsigned(zext_ln16_48_fu_550_p1) + unsigned(ap_const_lv7_30));
    add_ln16_17_fu_564_p2 <= std_logic_vector(unsigned(zext_ln16_48_fu_550_p1) + unsigned(ap_const_lv7_50));
    add_ln16_18_fu_607_p2 <= std_logic_vector(unsigned(zext_ln16_47_fu_604_p1) + unsigned(ap_const_lv8_70));
    add_ln16_19_fu_618_p2 <= std_logic_vector(unsigned(zext_ln16_47_fu_604_p1) + unsigned(ap_const_lv8_90));
    add_ln16_20_fu_658_p2 <= std_logic_vector(unsigned(zext_ln16_47_reg_1404) + unsigned(ap_const_lv8_B0));
    add_ln16_21_fu_629_p2 <= std_logic_vector(unsigned(tmp_reg_1359) + unsigned(zext_ln16_47_fu_604_p1));
    add_ln16_2_fu_1060_p2 <= std_logic_vector(unsigned(zext_ln16_33_fu_1057_p1) + unsigned(zext_ln16_32_fu_1054_p1));
    add_ln16_5_fu_1098_p2 <= std_logic_vector(unsigned(zext_ln16_36_fu_1095_p1) + unsigned(zext_ln16_35_fu_1092_p1));
    add_ln16_6_fu_1108_p2 <= std_logic_vector(unsigned(zext_ln16_37_fu_1104_p1) + unsigned(zext_ln16_34_fu_1089_p1));
    add_ln16_9_fu_1159_p2 <= std_logic_vector(unsigned(zext_ln16_40_fu_1156_p1) + unsigned(zext_ln16_39_fu_1153_p1));
    add_ln16_s_fu_973_p3 <= (xor_ln16_fu_968_p2 & trunc_ln16_reg_1336);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage3_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage4_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage5_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage6_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage7_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_1225_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln10_reg_1635, ap_block_pp0_stage0)
    begin
                ap_condition_1225 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln10_reg_1635 = ap_const_lv1_0));
    end process;


    ap_condition_1237_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_loop_init)
    begin
                ap_condition_1237 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_1242_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln10_reg_1635)
    begin
                ap_condition_1242 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln10_reg_1635 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage7_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone, icmp_ln10_fu_920_p2)
    begin
        if (((icmp_ln10_fu_920_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage7 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, icmp_ln10_reg_1635_pp0_iter1_reg, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln10_reg_1635_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter2_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0_1to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to2 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage7;

    ap_phi_mux_icmp_ln124_phi_fu_416_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln12_reg_1630, ap_loop_init, ap_condition_1225)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_1225)) then 
                ap_phi_mux_icmp_ln124_phi_fu_416_p4 <= icmp_ln12_reg_1630;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_icmp_ln124_phi_fu_416_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_icmp_ln124_phi_fu_416_p4 <= icmp_ln12_reg_1630;
            end if;
        else 
            ap_phi_mux_icmp_ln124_phi_fu_416_p4 <= icmp_ln12_reg_1630;
        end if; 
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_j3_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_loop_init, ap_block_pp0_stage0, j3_fu_122)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j3_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_j3_load <= j3_fu_122;
        end if; 
    end process;

    b_address0 <= b_address0_local;

    b_address0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0, ap_block_pp0_stage1, zext_ln16_54_fu_570_p1, ap_block_pp0_stage2, zext_ln16_58_fu_624_p1, ap_block_pp0_stage3, zext_ln16_62_fu_671_p1, ap_block_pp0_stage4, zext_ln16_53_fu_723_p1, ap_block_pp0_stage5, zext_ln16_57_fu_771_p1, ap_block_pp0_stage6, zext_ln16_61_fu_823_p1, ap_block_pp0_stage7, zext_ln16_63_fu_880_p1, zext_ln16_64_fu_984_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_address0_local <= zext_ln16_64_fu_984_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            b_address0_local <= zext_ln16_63_fu_880_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
            b_address0_local <= zext_ln16_61_fu_823_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
            b_address0_local <= zext_ln16_57_fu_771_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
            b_address0_local <= zext_ln16_53_fu_723_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
            b_address0_local <= zext_ln16_62_fu_671_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
            b_address0_local <= zext_ln16_58_fu_624_p1(8 - 1 downto 0);
        elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            b_address0_local <= zext_ln16_54_fu_570_p1(8 - 1 downto 0);
        else 
            b_address0_local <= "XXXXXXXX";
        end if; 
    end process;

    b_address1 <= b_address1_local;

    b_address1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage6, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage0, zext_ln12_fu_486_p1, ap_block_pp0_stage1, zext_ln16_52_fu_559_p1, ap_block_pp0_stage2, zext_ln16_56_fu_613_p1, ap_block_pp0_stage3, zext_ln16_60_fu_663_p1, ap_block_pp0_stage4, zext_ln16_51_fu_710_p1, ap_block_pp0_stage5, zext_ln16_55_fu_759_p1, ap_block_pp0_stage6, zext_ln16_59_fu_815_p1, ap_block_pp0_stage7, zext_ln16_50_fu_872_p1)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                b_address1_local <= zext_ln16_50_fu_872_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage6) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then 
                b_address1_local <= zext_ln16_59_fu_815_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage5) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then 
                b_address1_local <= zext_ln16_55_fu_759_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage4) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then 
                b_address1_local <= zext_ln16_51_fu_710_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage3) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then 
                b_address1_local <= zext_ln16_60_fu_663_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then 
                b_address1_local <= zext_ln16_56_fu_613_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                b_address1_local <= zext_ln16_52_fu_559_p1(8 - 1 downto 0);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                b_address1_local <= zext_ln12_fu_486_p1(8 - 1 downto 0);
            else 
                b_address1_local <= "XXXXXXXX";
            end if;
        else 
            b_address1_local <= "XXXXXXXX";
        end if; 
    end process;

    b_ce0 <= b_ce0_local;

    b_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage7_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            b_ce0_local <= ap_const_logic_1;
        else 
            b_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    b_ce1 <= b_ce1_local;

    b_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_11001, ap_block_pp0_stage7_11001, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) 
    or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            b_ce1_local <= ap_const_logic_1;
        else 
            b_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_520_p1 <= i_fu_512_p3(4 - 1 downto 0);
    grp_fu_1227_p0 <= grp_fu_1227_p00(8 - 1 downto 0);
    grp_fu_1227_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_437),16));
    grp_fu_1227_p1 <= grp_fu_1227_p10(8 - 1 downto 0);
    grp_fu_1227_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_432),16));
    grp_fu_1227_p2 <= grp_fu_1227_p20(16 - 1 downto 0);
    grp_fu_1227_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_2_fu_893_p2),17));
    grp_fu_1235_p0 <= grp_fu_1235_p00(8 - 1 downto 0);
    grp_fu_1235_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_441),16));
    grp_fu_1235_p1 <= grp_fu_1235_p10(8 - 1 downto 0);
    grp_fu_1235_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_446),16));
    grp_fu_1235_p2 <= grp_fu_1235_p20(16 - 1 downto 0);
    grp_fu_1235_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_4_fu_993_p2),17));
    grp_fu_1243_p0 <= grp_fu_1243_p00(8 - 1 downto 0);
    grp_fu_1243_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_424),16));
    grp_fu_1243_p1 <= grp_fu_1243_p10(8 - 1 downto 0);
    grp_fu_1243_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_428),16));
    grp_fu_1243_p2 <= grp_fu_1243_p20(16 - 1 downto 0);
    grp_fu_1243_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_1_fu_1017_p2),17));
    grp_fu_1252_p0 <= grp_fu_1252_p00(8 - 1 downto 0);
    grp_fu_1252_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_7_reg_1444),16));
    grp_fu_1252_p1 <= grp_fu_1252_p10(8 - 1 downto 0);
    grp_fu_1252_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_451),16));
    grp_fu_1252_p2 <= grp_fu_1252_p20(16 - 1 downto 0);
    grp_fu_1252_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_6_fu_1041_p2),17));
    grp_fu_1261_p0 <= grp_fu_1261_p00(8 - 1 downto 0);
    grp_fu_1261_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_9_reg_1449),16));
    grp_fu_1261_p1 <= grp_fu_1261_p10(8 - 1 downto 0);
    grp_fu_1261_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_9_reg_1464),16));
    grp_fu_1261_p2 <= grp_fu_1261_p20(16 - 1 downto 0);
    grp_fu_1261_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_8_fu_1076_p2),17));
    grp_fu_1269_p0 <= grp_fu_1269_p00(8 - 1 downto 0);
    grp_fu_1269_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_11_reg_1500),16));
    grp_fu_1269_p1 <= grp_fu_1269_p10(8 - 1 downto 0);
    grp_fu_1269_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_11_reg_1469),16));
    grp_fu_1269_p2 <= grp_fu_1269_p20(16 - 1 downto 0);
    grp_fu_1269_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_10_fu_1123_p2),17));
    grp_fu_1278_p0 <= grp_fu_1278_p00(8 - 1 downto 0);
    grp_fu_1278_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_13_reg_1505),16));
    grp_fu_1278_p1 <= grp_fu_1278_p10(8 - 1 downto 0);
    grp_fu_1278_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_13_reg_1525),16));
    grp_fu_1278_p2 <= grp_fu_1278_p20(16 - 1 downto 0);
    grp_fu_1278_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_12_fu_1143_p2),17));
    grp_fu_1286_p0 <= grp_fu_1286_p00(8 - 1 downto 0);
    grp_fu_1286_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_456),16));
    grp_fu_1286_p1 <= grp_fu_1286_p10(8 - 1 downto 0);
    grp_fu_1286_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_15_reg_1530),16));
    grp_fu_1286_p2 <= grp_fu_1286_p20(16 - 1 downto 0);
    grp_fu_1286_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln16_14_fu_1171_p2),17));
    i_fu_512_p3 <= 
        add_ln10_fu_506_p2 when (icmp_ln124_reg_413(0) = '1') else 
        i2_fu_118;
    icmp_ln10_fu_920_p2 <= "1" when (indvar_flatten1_fu_114 = ap_const_lv8_FF) else "0";
    icmp_ln12_fu_914_p2 <= "1" when (j_fu_903_p2 = ap_const_lv5_10) else "0";
    j_fu_903_p2 <= std_logic_vector(unsigned(select_ln10_reg_1316) + unsigned(ap_const_lv5_1));
    mul_ln16_10_fu_1123_p0 <= mul_ln16_10_fu_1123_p00(8 - 1 downto 0);
    mul_ln16_10_fu_1123_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_10_reg_1620),16));
    mul_ln16_10_fu_1123_p1 <= mul_ln16_10_fu_1123_p10(8 - 1 downto 0);
    mul_ln16_10_fu_1123_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_10_reg_1654),16));
    mul_ln16_12_fu_1143_p0 <= mul_ln16_12_fu_1143_p00(8 - 1 downto 0);
    mul_ln16_12_fu_1143_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_12_reg_1625),16));
    mul_ln16_12_fu_1143_p1 <= mul_ln16_12_fu_1143_p10(8 - 1 downto 0);
    mul_ln16_12_fu_1143_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_12_reg_1689),16));
    mul_ln16_14_fu_1171_p0 <= mul_ln16_14_fu_1171_p00(8 - 1 downto 0);
    mul_ln16_14_fu_1171_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_14_reg_1674),16));
    mul_ln16_14_fu_1171_p1 <= mul_ln16_14_fu_1171_p10(8 - 1 downto 0);
    mul_ln16_14_fu_1171_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(a_load_14_reg_1694),16));
    mul_ln16_1_fu_1017_p0 <= mul_ln16_1_fu_1017_p00(8 - 1 downto 0);
    mul_ln16_1_fu_1017_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_424),16));
    mul_ln16_1_fu_1017_p1 <= mul_ln16_1_fu_1017_p10(8 - 1 downto 0);
    mul_ln16_1_fu_1017_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_432),16));
    mul_ln16_2_fu_893_p0 <= mul_ln16_2_fu_893_p00(8 - 1 downto 0);
    mul_ln16_2_fu_893_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_437),16));
    mul_ln16_2_fu_893_p1 <= mul_ln16_2_fu_893_p10(8 - 1 downto 0);
    mul_ln16_2_fu_893_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_446),16));
    mul_ln16_4_fu_993_p0 <= mul_ln16_4_fu_993_p00(8 - 1 downto 0);
    mul_ln16_4_fu_993_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_456),16));
    mul_ln16_4_fu_993_p1 <= mul_ln16_4_fu_993_p10(8 - 1 downto 0);
    mul_ln16_4_fu_993_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_428),16));
    mul_ln16_6_fu_1041_p0 <= mul_ln16_6_fu_1041_p00(8 - 1 downto 0);
    mul_ln16_6_fu_1041_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_441),16));
    mul_ln16_6_fu_1041_p1 <= mul_ln16_6_fu_1041_p10(8 - 1 downto 0);
    mul_ln16_6_fu_1041_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_446),16));
    mul_ln16_8_fu_1076_p0 <= mul_ln16_8_fu_1076_p00(8 - 1 downto 0);
    mul_ln16_8_fu_1076_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_load_8_reg_1580),16));
    mul_ln16_8_fu_1076_p1 <= mul_ln16_8_fu_1076_p10(8 - 1 downto 0);
    mul_ln16_8_fu_1076_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reg_451),16));
    prod_address0 <= zext_ln16_65_fu_1206_p1(8 - 1 downto 0);
    prod_ce0 <= prod_ce0_local;

    prod_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            prod_ce0_local <= ap_const_logic_1;
        else 
            prod_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    prod_d0 <= zext_ln16_46_fu_1222_p1;
    prod_we0 <= prod_we0_local;

    prod_we0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            prod_we0_local <= ap_const_logic_1;
        else 
            prod_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln10_fu_478_p3 <= 
        ap_const_lv5_0 when (ap_phi_mux_icmp_ln124_phi_fu_416_p4(0) = '1') else 
        ap_sig_allocacmp_j3_load;
        sext_ln16_1_fu_820_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_cast_reg_1490),8));

        sext_ln16_2_fu_668_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln16_17_reg_1384),8));

        sext_ln16_3_fu_877_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_cast_reg_1479),8));

        sext_ln16_4_fu_980_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln16_s_fu_973_p3),8));

        sext_ln16_fu_756_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_cast_reg_1479),7));

    tmp_10_cast_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_847_p3),64));
    tmp_10_fu_646_p3 <= (empty_reg_1341 & ap_const_lv4_B);
    tmp_11_cast_fu_653_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_646_p3),64));
    tmp_11_fu_936_p3 <= (empty_reg_1341 & ap_const_lv4_C);
    tmp_12_cast_fu_943_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_936_p3),64));
    tmp_12_fu_676_p3 <= (empty_reg_1341 & ap_const_lv4_D);
    tmp_13_cast_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_676_p3),64));
    tmp_13_fu_948_p3 <= (empty_reg_1341 & ap_const_lv4_E);
    tmp_14_cast_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_13_fu_948_p3),64));
    tmp_14_fu_688_p3 <= (empty_reg_1341 & ap_const_lv4_F);
    tmp_15_cast_fu_695_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_14_fu_688_p3),64));
    tmp_16_cast_fu_703_p3 <= (ap_const_lv1_1 & select_ln10_reg_1316);
    tmp_17_cast_fu_715_p3 <= (ap_const_lv1_1 & zext_ln16_49_fu_700_p1);
    tmp_19_cast_fu_764_p3 <= (ap_const_lv1_1 & zext_ln16_48_reg_1374);
    tmp_1_cast_fu_735_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_728_p3),64));
    tmp_1_fu_728_p3 <= (empty_reg_1341 & ap_const_lv4_1);
    tmp_20_cast_fu_808_p3 <= (ap_const_lv3_5 & select_ln10_reg_1316);
    tmp_2_cast_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_740_p3),64));
    tmp_2_fu_740_p3 <= (empty_reg_1341 & ap_const_lv4_2);
    tmp_3_cast_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_537_p3),64));
    tmp_3_fu_537_p3 <= (empty_fu_520_p1 & ap_const_lv4_3);
    tmp_4_cast_fu_787_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_780_p3),64));
    tmp_4_fu_780_p3 <= (empty_reg_1341 & ap_const_lv4_4);
    tmp_5_cast_fu_587_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_580_p3),64));
    tmp_5_fu_580_p3 <= (empty_reg_1341 & ap_const_lv4_5);
    tmp_6_cast_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_792_p3),64));
    tmp_6_fu_792_p3 <= (empty_reg_1341 & ap_const_lv4_6);
    tmp_7_cast_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_592_p3),64));
    tmp_7_fu_592_p3 <= (empty_reg_1341 & ap_const_lv4_7);
    tmp_8_cast_fu_842_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_835_p3),64));
    tmp_8_fu_835_p3 <= (empty_reg_1341 & ap_const_lv4_8);
    tmp_9_cast_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_634_p3),64));
    tmp_9_fu_634_p3 <= (empty_reg_1341 & ap_const_lv4_9);
    tmp_cast_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_524_p3),64));
    tmp_fu_524_p3 <= (empty_fu_520_p1 & ap_const_lv4_0);
    tmp_s_fu_847_p3 <= (empty_reg_1341 & ap_const_lv4_A);
    trunc_ln16_fu_499_p1 <= select_ln10_fu_478_p3(4 - 1 downto 0);
    xor_ln16_fu_968_p2 <= (bit_sel_reg_1331 xor ap_const_lv1_1);
    zext_ln12_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_fu_478_p3),64));
    zext_ln16_32_fu_1054_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1243_p3),18));
    zext_ln16_33_fu_1057_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_1_reg_1679),18));
    zext_ln16_34_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_2_reg_1729),19));
    zext_ln16_35_fu_1092_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_3_reg_1709),18));
    zext_ln16_36_fu_1095_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1252_p3),18));
    zext_ln16_37_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_5_fu_1098_p2),19));
    zext_ln16_38_fu_1210_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_6_reg_1749),20));
    zext_ln16_39_fu_1153_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_7_reg_1769),18));
    zext_ln16_40_fu_1156_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1269_p3),18));
    zext_ln16_41_fu_1181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_9_reg_1779),19));
    zext_ln16_42_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_10_reg_1789),18));
    zext_ln16_43_fu_1187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1286_p3),18));
    zext_ln16_44_fu_1196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_12_fu_1190_p2),19));
    zext_ln16_45_fu_1213_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_13_reg_1794),20));
    zext_ln16_46_fu_1222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_14_fu_1216_p2),32));
    zext_ln16_47_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_reg_1316),8));
    zext_ln16_48_fu_550_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_reg_1316),7));
    zext_ln16_49_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln10_reg_1316),6));
    zext_ln16_50_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_15_fu_867_p2),64));
    zext_ln16_51_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_16_cast_fu_703_p3),64));
    zext_ln16_52_fu_559_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_16_fu_553_p2),64));
    zext_ln16_53_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_cast_fu_715_p3),64));
    zext_ln16_54_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_17_fu_564_p2),64));
    zext_ln16_55_fu_759_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln16_fu_756_p1),64));
    zext_ln16_56_fu_613_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_18_fu_607_p2),64));
    zext_ln16_57_fu_771_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_cast_fu_764_p3),64));
    zext_ln16_58_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_19_fu_618_p2),64));
    zext_ln16_59_fu_815_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_20_cast_fu_808_p3),64));
    zext_ln16_60_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_20_fu_658_p2),64));
    zext_ln16_61_fu_823_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln16_1_fu_820_p1),64));
    zext_ln16_62_fu_671_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln16_2_fu_668_p1),64));
    zext_ln16_63_fu_880_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln16_3_fu_877_p1),64));
    zext_ln16_64_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln16_4_fu_980_p1),64));
    zext_ln16_65_fu_1206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln16_21_reg_1419_pp0_iter1_reg),64));
end behav;
