// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrix_mult_matrix_mult,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.343063,HLS_SYN_LAT=2058,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=428,HLS_SYN_LUT=1074,HLS_VERSION=2024_1}" *)

module matrix_mult (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_q0,
        a_address1,
        a_ce1,
        a_q1,
        b_address0,
        b_ce0,
        b_q0,
        b_address1,
        b_ce1,
        b_q1,
        prod_address0,
        prod_ce0,
        prod_we0,
        prod_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
input  [7:0] a_q0;
output  [7:0] a_address1;
output   a_ce1;
input  [7:0] a_q1;
output  [7:0] b_address0;
output   b_ce0;
input  [7:0] b_q0;
output  [7:0] b_address1;
output   b_ce1;
input  [7:0] b_q1;
output  [7:0] prod_address0;
output   prod_ce0;
output   prod_we0;
output  [31:0] prod_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
wire   [0:0] icmp_ln10_fu_920_p2;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln124_reg_413;
reg   [7:0] reg_424;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] reg_428;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage7_11001;
reg   [7:0] reg_432;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg   [7:0] reg_437;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
reg   [7:0] reg_441;
reg   [7:0] reg_446;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [7:0] reg_451;
reg   [7:0] reg_456;
wire   [4:0] select_ln10_fu_478_p3;
reg   [4:0] select_ln10_reg_1316;
reg   [0:0] bit_sel_reg_1331;
wire   [3:0] trunc_ln16_fu_499_p1;
reg   [3:0] trunc_ln16_reg_1336;
wire   [3:0] empty_fu_520_p1;
reg   [3:0] empty_reg_1341;
wire   [7:0] tmp_fu_524_p3;
reg   [7:0] tmp_reg_1359;
wire   [6:0] zext_ln16_48_fu_550_p1;
reg   [6:0] zext_ln16_48_reg_1374;
wire  signed [6:0] add_ln16_17_fu_564_p2;
reg  signed [6:0] add_ln16_17_reg_1384;
wire   [7:0] zext_ln16_47_fu_604_p1;
reg   [7:0] zext_ln16_47_reg_1404;
wire   [7:0] add_ln16_21_fu_629_p2;
reg   [7:0] add_ln16_21_reg_1419;
reg   [7:0] add_ln16_21_reg_1419_pp0_iter1_reg;
reg   [7:0] b_load_7_reg_1444;
reg   [7:0] b_load_9_reg_1449;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
reg   [7:0] a_load_9_reg_1464;
reg   [7:0] a_load_11_reg_1469;
wire   [5:0] zext_ln16_49_fu_700_p1;
reg   [5:0] zext_ln16_49_reg_1474;
wire  signed [5:0] tmp_16_cast_fu_703_p3;
reg  signed [5:0] tmp_16_cast_reg_1479;
wire  signed [6:0] tmp_17_cast_fu_715_p3;
reg  signed [6:0] tmp_17_cast_reg_1490;
reg   [7:0] b_load_11_reg_1500;
reg   [7:0] b_load_13_reg_1505;
reg   [7:0] a_load_13_reg_1525;
reg   [7:0] a_load_15_reg_1530;
reg   [7:0] b_load_8_reg_1580;
reg   [7:0] b_load_10_reg_1620;
reg   [7:0] b_load_12_reg_1625;
wire   [0:0] icmp_ln12_fu_914_p2;
reg   [0:0] icmp_ln12_reg_1630;
reg   [0:0] icmp_ln10_reg_1635;
reg   [0:0] icmp_ln10_reg_1635_pp0_iter1_reg;
reg   [7:0] a_load_10_reg_1654;
reg   [7:0] b_load_14_reg_1674;
wire   [16:0] grp_fu_1227_p3;
reg   [16:0] add_ln16_1_reg_1679;
reg   [7:0] a_load_12_reg_1689;
reg   [7:0] a_load_14_reg_1694;
wire   [16:0] grp_fu_1235_p3;
reg   [16:0] add_ln16_3_reg_1709;
wire   [17:0] add_ln16_2_fu_1060_p2;
reg   [17:0] add_ln16_2_reg_1729;
wire   [18:0] add_ln16_6_fu_1108_p2;
reg   [18:0] add_ln16_6_reg_1749;
wire   [16:0] grp_fu_1261_p3;
reg   [16:0] add_ln16_7_reg_1769;
wire   [17:0] add_ln16_9_fu_1159_p2;
reg   [17:0] add_ln16_9_reg_1779;
wire   [16:0] grp_fu_1278_p3;
reg   [16:0] add_ln16_10_reg_1789;
wire   [18:0] add_ln16_13_fu_1200_p2;
reg   [18:0] add_ln16_13_reg_1794;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
reg   [0:0] ap_phi_mux_icmp_ln124_phi_fu_416_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln12_fu_486_p1;
wire   [63:0] tmp_cast_fu_532_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] tmp_3_cast_fu_545_p1;
wire   [63:0] zext_ln16_52_fu_559_p1;
wire   [63:0] zext_ln16_54_fu_570_p1;
wire   [63:0] tmp_5_cast_fu_587_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] tmp_7_cast_fu_599_p1;
wire   [63:0] zext_ln16_56_fu_613_p1;
wire   [63:0] zext_ln16_58_fu_624_p1;
wire   [63:0] tmp_9_cast_fu_641_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] tmp_11_cast_fu_653_p1;
wire   [63:0] zext_ln16_60_fu_663_p1;
wire   [63:0] zext_ln16_62_fu_671_p1;
wire   [63:0] tmp_13_cast_fu_683_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] tmp_15_cast_fu_695_p1;
wire   [63:0] zext_ln16_51_fu_710_p1;
wire   [63:0] zext_ln16_53_fu_723_p1;
wire   [63:0] tmp_1_cast_fu_735_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] tmp_2_cast_fu_747_p1;
wire   [63:0] zext_ln16_55_fu_759_p1;
wire   [63:0] zext_ln16_57_fu_771_p1;
wire   [63:0] tmp_4_cast_fu_787_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] tmp_6_cast_fu_799_p1;
wire   [63:0] zext_ln16_59_fu_815_p1;
wire   [63:0] zext_ln16_61_fu_823_p1;
wire   [63:0] tmp_8_cast_fu_842_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] tmp_10_cast_fu_854_p1;
wire   [63:0] zext_ln16_50_fu_872_p1;
wire   [63:0] zext_ln16_63_fu_880_p1;
wire   [63:0] tmp_12_cast_fu_943_p1;
wire   [63:0] tmp_14_cast_fu_955_p1;
wire   [63:0] zext_ln16_64_fu_984_p1;
wire   [63:0] zext_ln16_65_fu_1206_p1;
reg   [7:0] indvar_flatten1_fu_114;
wire   [7:0] add_ln10_1_fu_908_p2;
reg   [4:0] i2_fu_118;
wire   [4:0] i_fu_512_p3;
reg   [4:0] j3_fu_122;
wire   [4:0] j_fu_903_p2;
reg   [4:0] ap_sig_allocacmp_j3_load;
reg    b_ce1_local;
reg   [7:0] b_address1_local;
reg    b_ce0_local;
reg   [7:0] b_address0_local;
reg    a_ce1_local;
reg   [7:0] a_address1_local;
reg    a_ce0_local;
reg   [7:0] a_address0_local;
reg    prod_we0_local;
wire   [31:0] zext_ln16_46_fu_1222_p1;
reg    prod_ce0_local;
wire   [4:0] add_ln10_fu_506_p2;
wire   [7:0] tmp_3_fu_537_p3;
wire   [6:0] add_ln16_16_fu_553_p2;
wire   [7:0] tmp_5_fu_580_p3;
wire   [7:0] tmp_7_fu_592_p3;
wire   [7:0] add_ln16_18_fu_607_p2;
wire   [7:0] add_ln16_19_fu_618_p2;
wire   [7:0] tmp_9_fu_634_p3;
wire   [7:0] tmp_10_fu_646_p3;
wire   [7:0] add_ln16_20_fu_658_p2;
wire  signed [7:0] sext_ln16_2_fu_668_p1;
wire   [7:0] tmp_12_fu_676_p3;
wire   [7:0] tmp_14_fu_688_p3;
wire   [7:0] tmp_1_fu_728_p3;
wire   [7:0] tmp_2_fu_740_p3;
wire  signed [6:0] sext_ln16_fu_756_p1;
wire   [7:0] tmp_19_cast_fu_764_p3;
wire   [7:0] tmp_4_fu_780_p3;
wire   [7:0] tmp_6_fu_792_p3;
wire   [7:0] tmp_20_cast_fu_808_p3;
wire  signed [7:0] sext_ln16_1_fu_820_p1;
wire   [7:0] tmp_8_fu_835_p3;
wire   [7:0] tmp_s_fu_847_p3;
wire   [5:0] add_ln16_15_fu_867_p2;
wire  signed [7:0] sext_ln16_3_fu_877_p1;
wire   [7:0] mul_ln16_2_fu_893_p0;
wire   [7:0] mul_ln16_2_fu_893_p1;
wire   [15:0] mul_ln16_2_fu_893_p2;
wire   [7:0] tmp_11_fu_936_p3;
wire   [7:0] tmp_13_fu_948_p3;
wire   [0:0] xor_ln16_fu_968_p2;
wire   [4:0] add_ln16_s_fu_973_p3;
wire  signed [7:0] sext_ln16_4_fu_980_p1;
wire   [7:0] mul_ln16_4_fu_993_p0;
wire   [7:0] mul_ln16_4_fu_993_p1;
wire   [15:0] mul_ln16_4_fu_993_p2;
wire   [7:0] mul_ln16_1_fu_1017_p0;
wire   [7:0] mul_ln16_1_fu_1017_p1;
wire   [15:0] mul_ln16_1_fu_1017_p2;
wire   [7:0] mul_ln16_6_fu_1041_p0;
wire   [7:0] mul_ln16_6_fu_1041_p1;
wire   [15:0] mul_ln16_6_fu_1041_p2;
wire   [16:0] grp_fu_1243_p3;
wire   [17:0] zext_ln16_33_fu_1057_p1;
wire   [17:0] zext_ln16_32_fu_1054_p1;
wire   [7:0] mul_ln16_8_fu_1076_p0;
wire   [7:0] mul_ln16_8_fu_1076_p1;
wire   [15:0] mul_ln16_8_fu_1076_p2;
wire   [16:0] grp_fu_1252_p3;
wire   [17:0] zext_ln16_36_fu_1095_p1;
wire   [17:0] zext_ln16_35_fu_1092_p1;
wire   [17:0] add_ln16_5_fu_1098_p2;
wire   [18:0] zext_ln16_37_fu_1104_p1;
wire   [18:0] zext_ln16_34_fu_1089_p1;
wire   [7:0] mul_ln16_10_fu_1123_p0;
wire   [7:0] mul_ln16_10_fu_1123_p1;
wire   [15:0] mul_ln16_10_fu_1123_p2;
wire   [7:0] mul_ln16_12_fu_1143_p0;
wire   [7:0] mul_ln16_12_fu_1143_p1;
wire   [15:0] mul_ln16_12_fu_1143_p2;
wire   [16:0] grp_fu_1269_p3;
wire   [17:0] zext_ln16_40_fu_1156_p1;
wire   [17:0] zext_ln16_39_fu_1153_p1;
wire   [7:0] mul_ln16_14_fu_1171_p0;
wire   [7:0] mul_ln16_14_fu_1171_p1;
wire   [15:0] mul_ln16_14_fu_1171_p2;
wire   [16:0] grp_fu_1286_p3;
wire   [17:0] zext_ln16_43_fu_1187_p1;
wire   [17:0] zext_ln16_42_fu_1184_p1;
wire   [17:0] add_ln16_12_fu_1190_p2;
wire   [18:0] zext_ln16_44_fu_1196_p1;
wire   [18:0] zext_ln16_41_fu_1181_p1;
wire   [19:0] zext_ln16_45_fu_1213_p1;
wire   [19:0] zext_ln16_38_fu_1210_p1;
wire   [19:0] add_ln16_14_fu_1216_p2;
wire   [7:0] grp_fu_1227_p0;
wire   [7:0] grp_fu_1227_p1;
wire   [15:0] grp_fu_1227_p2;
wire   [7:0] grp_fu_1235_p0;
wire   [7:0] grp_fu_1235_p1;
wire   [15:0] grp_fu_1235_p2;
wire   [7:0] grp_fu_1243_p0;
wire   [7:0] grp_fu_1243_p1;
wire   [15:0] grp_fu_1243_p2;
wire   [7:0] grp_fu_1252_p0;
wire   [7:0] grp_fu_1252_p1;
wire   [15:0] grp_fu_1252_p2;
wire   [7:0] grp_fu_1261_p0;
wire   [7:0] grp_fu_1261_p1;
wire   [15:0] grp_fu_1261_p2;
wire   [7:0] grp_fu_1269_p0;
wire   [7:0] grp_fu_1269_p1;
wire   [15:0] grp_fu_1269_p2;
wire   [7:0] grp_fu_1278_p0;
wire   [7:0] grp_fu_1278_p1;
wire   [15:0] grp_fu_1278_p2;
wire   [7:0] grp_fu_1286_p0;
wire   [7:0] grp_fu_1286_p1;
wire   [15:0] grp_fu_1286_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    ap_idle_pp0_0to1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_1to2;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [15:0] grp_fu_1227_p00;
wire   [15:0] grp_fu_1227_p10;
wire   [16:0] grp_fu_1227_p20;
wire   [15:0] grp_fu_1235_p00;
wire   [15:0] grp_fu_1235_p10;
wire   [16:0] grp_fu_1235_p20;
wire   [15:0] grp_fu_1243_p00;
wire   [15:0] grp_fu_1243_p10;
wire   [16:0] grp_fu_1243_p20;
wire   [15:0] grp_fu_1252_p00;
wire   [15:0] grp_fu_1252_p10;
wire   [16:0] grp_fu_1252_p20;
wire   [15:0] grp_fu_1261_p00;
wire   [15:0] grp_fu_1261_p10;
wire   [16:0] grp_fu_1261_p20;
wire   [15:0] grp_fu_1269_p00;
wire   [15:0] grp_fu_1269_p10;
wire   [16:0] grp_fu_1269_p20;
wire   [15:0] grp_fu_1278_p00;
wire   [15:0] grp_fu_1278_p10;
wire   [16:0] grp_fu_1278_p20;
wire   [15:0] grp_fu_1286_p00;
wire   [15:0] grp_fu_1286_p10;
wire   [16:0] grp_fu_1286_p20;
wire   [15:0] mul_ln16_10_fu_1123_p00;
wire   [15:0] mul_ln16_10_fu_1123_p10;
wire   [15:0] mul_ln16_12_fu_1143_p00;
wire   [15:0] mul_ln16_12_fu_1143_p10;
wire   [15:0] mul_ln16_14_fu_1171_p00;
wire   [15:0] mul_ln16_14_fu_1171_p10;
wire   [15:0] mul_ln16_1_fu_1017_p00;
wire   [15:0] mul_ln16_1_fu_1017_p10;
wire   [15:0] mul_ln16_2_fu_893_p00;
wire   [15:0] mul_ln16_2_fu_893_p10;
wire   [15:0] mul_ln16_4_fu_993_p00;
wire   [15:0] mul_ln16_4_fu_993_p10;
wire   [15:0] mul_ln16_6_fu_1041_p00;
wire   [15:0] mul_ln16_6_fu_1041_p10;
wire   [15:0] mul_ln16_8_fu_1076_p00;
wire   [15:0] mul_ln16_8_fu_1076_p10;
reg    ap_condition_1225;
reg    ap_condition_1237;
reg    ap_condition_1242;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 indvar_flatten1_fu_114 = 8'd0;
#0 i2_fu_118 = 5'd0;
#0 j3_fu_122 = 5'd0;
#0 ap_done_reg = 1'b0;
end

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U1(
    .din0(mul_ln16_2_fu_893_p0),
    .din1(mul_ln16_2_fu_893_p1),
    .dout(mul_ln16_2_fu_893_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U2(
    .din0(mul_ln16_4_fu_993_p0),
    .din1(mul_ln16_4_fu_993_p1),
    .dout(mul_ln16_4_fu_993_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U3(
    .din0(mul_ln16_1_fu_1017_p0),
    .din1(mul_ln16_1_fu_1017_p1),
    .dout(mul_ln16_1_fu_1017_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U4(
    .din0(mul_ln16_6_fu_1041_p0),
    .din1(mul_ln16_6_fu_1041_p1),
    .dout(mul_ln16_6_fu_1041_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U5(
    .din0(mul_ln16_8_fu_1076_p0),
    .din1(mul_ln16_8_fu_1076_p1),
    .dout(mul_ln16_8_fu_1076_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U6(
    .din0(mul_ln16_10_fu_1123_p0),
    .din1(mul_ln16_10_fu_1123_p1),
    .dout(mul_ln16_10_fu_1123_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U7(
    .din0(mul_ln16_12_fu_1143_p0),
    .din1(mul_ln16_12_fu_1143_p1),
    .dout(mul_ln16_12_fu_1143_p2)
);

matrix_mult_mul_8ns_8ns_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
mul_8ns_8ns_16_1_1_U8(
    .din0(mul_ln16_14_fu_1171_p0),
    .din1(mul_ln16_14_fu_1171_p1),
    .dout(mul_ln16_14_fu_1171_p2)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1227_p0),
    .din1(grp_fu_1227_p1),
    .din2(grp_fu_1227_p2),
    .ce(1'b1),
    .dout(grp_fu_1227_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1235_p0),
    .din1(grp_fu_1235_p1),
    .din2(grp_fu_1235_p2),
    .ce(1'b1),
    .dout(grp_fu_1235_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1243_p0),
    .din1(grp_fu_1243_p1),
    .din2(grp_fu_1243_p2),
    .ce(1'b1),
    .dout(grp_fu_1243_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1252_p0),
    .din1(grp_fu_1252_p1),
    .din2(grp_fu_1252_p2),
    .ce(1'b1),
    .dout(grp_fu_1252_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1261_p0),
    .din1(grp_fu_1261_p1),
    .din2(grp_fu_1261_p2),
    .ce(1'b1),
    .dout(grp_fu_1261_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1269_p0),
    .din1(grp_fu_1269_p1),
    .din2(grp_fu_1269_p2),
    .ce(1'b1),
    .dout(grp_fu_1269_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1278_p0),
    .din1(grp_fu_1278_p1),
    .din2(grp_fu_1278_p2),
    .ce(1'b1),
    .dout(grp_fu_1278_p3)
);

matrix_mult_mac_muladd_8ns_8ns_16ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_8ns_8ns_16ns_17_4_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1286_p0),
    .din1(grp_fu_1286_p1),
    .din2(grp_fu_1286_p2),
    .ce(1'b1),
    .dout(grp_fu_1286_p3)
);

matrix_mult_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0)) | ((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1)))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1237)) begin
            i2_fu_118 <= 5'd0;
        end else if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            i2_fu_118 <= i_fu_512_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1242)) begin
            icmp_ln124_reg_413 <= icmp_ln12_reg_1630;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_init == 1'b1))) begin
            icmp_ln124_reg_413 <= 1'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1237)) begin
            indvar_flatten1_fu_114 <= 8'd0;
        end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            indvar_flatten1_fu_114 <= add_ln10_1_fu_908_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if ((1'b1 == ap_condition_1237)) begin
            j3_fu_122 <= 5'd0;
        end else if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            j3_fu_122 <= j_fu_903_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            reg_432 <= a_q1;
        end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            reg_432 <= a_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            reg_441 <= b_q1;
        end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            reg_441 <= b_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        reg_446 <= a_q0;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_446 <= a_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_451 <= a_q1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_451 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_load_10_reg_1654 <= a_q0;
        add_ln16_1_reg_1679 <= grp_fu_1227_p3;
        b_load_14_reg_1674 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_load_11_reg_1469 <= a_q0;
        a_load_9_reg_1464 <= a_q1;
        b_load_11_reg_1500 <= b_q1;
        b_load_13_reg_1505 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_load_12_reg_1689 <= a_q1;
        a_load_14_reg_1694 <= a_q0;
        add_ln16_3_reg_1709 <= grp_fu_1235_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_load_13_reg_1525 <= a_q1;
        a_load_15_reg_1530 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        add_ln16_10_reg_1789 <= grp_fu_1278_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln16_13_reg_1794 <= add_ln16_13_fu_1200_p2;
        icmp_ln10_reg_1635 <= icmp_ln10_fu_920_p2;
        icmp_ln10_reg_1635_pp0_iter1_reg <= icmp_ln10_reg_1635;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln16_17_reg_1384 <= add_ln16_17_fu_564_p2;
        empty_reg_1341 <= empty_fu_520_p1;
        tmp_reg_1359[7 : 4] <= tmp_fu_524_p3[7 : 4];
        zext_ln16_48_reg_1374[4 : 0] <= zext_ln16_48_fu_550_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln16_21_reg_1419 <= add_ln16_21_fu_629_p2;
        add_ln16_21_reg_1419_pp0_iter1_reg <= add_ln16_21_reg_1419;
        add_ln16_2_reg_1729 <= add_ln16_2_fu_1060_p2;
        zext_ln16_47_reg_1404[4 : 0] <= zext_ln16_47_fu_604_p1[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln16_6_reg_1749 <= add_ln16_6_fu_1108_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln16_7_reg_1769 <= grp_fu_1261_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln16_9_reg_1779 <= add_ln16_9_fu_1159_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        b_load_10_reg_1620 <= b_q1;
        b_load_12_reg_1625 <= b_q0;
        icmp_ln12_reg_1630 <= icmp_ln12_fu_914_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        b_load_7_reg_1444 <= b_q1;
        b_load_9_reg_1449 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        b_load_8_reg_1580 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bit_sel_reg_1331 <= select_ln10_fu_478_p3[5'd4];
        select_ln10_reg_1316 <= select_ln10_fu_478_p3;
        trunc_ln16_reg_1336 <= trunc_ln16_fu_499_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_424 <= b_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_428 <= a_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_437 <= b_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_456 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        tmp_16_cast_reg_1479[4 : 0] <= tmp_16_cast_fu_703_p3[4 : 0];
        tmp_17_cast_reg_1490[4 : 0] <= tmp_17_cast_fu_715_p3[4 : 0];
        zext_ln16_49_reg_1474[4 : 0] <= zext_ln16_49_fu_700_p1[4 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address0_local = tmp_14_cast_fu_955_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        a_address0_local = tmp_10_cast_fu_854_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        a_address0_local = tmp_6_cast_fu_799_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_address0_local = tmp_2_cast_fu_747_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_address0_local = tmp_15_cast_fu_695_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_address0_local = tmp_11_cast_fu_653_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address0_local = tmp_7_cast_fu_599_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address0_local = tmp_3_cast_fu_545_p1;
    end else begin
        a_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_address1_local = tmp_12_cast_fu_943_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        a_address1_local = tmp_8_cast_fu_842_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        a_address1_local = tmp_4_cast_fu_787_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        a_address1_local = tmp_1_cast_fu_735_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        a_address1_local = tmp_13_cast_fu_683_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        a_address1_local = tmp_9_cast_fu_641_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        a_address1_local = tmp_5_cast_fu_587_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        a_address1_local = tmp_cast_fu_532_p1;
    end else begin
        a_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        a_ce0_local = 1'b1;
    end else begin
        a_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        a_ce1_local = 1'b1;
    end else begin
        a_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_920_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln10_reg_1635_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to2 = 1'b1;
    end else begin
        ap_idle_pp0_1to2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_1225)) begin
            ap_phi_mux_icmp_ln124_phi_fu_416_p4 = icmp_ln12_reg_1630;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln124_phi_fu_416_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln124_phi_fu_416_p4 = icmp_ln12_reg_1630;
        end
    end else begin
        ap_phi_mux_icmp_ln124_phi_fu_416_p4 = icmp_ln12_reg_1630;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j3_load = 5'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_122;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_address0_local = zext_ln16_64_fu_984_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        b_address0_local = zext_ln16_63_fu_880_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        b_address0_local = zext_ln16_61_fu_823_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        b_address0_local = zext_ln16_57_fu_771_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        b_address0_local = zext_ln16_53_fu_723_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        b_address0_local = zext_ln16_62_fu_671_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        b_address0_local = zext_ln16_58_fu_624_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        b_address0_local = zext_ln16_54_fu_570_p1;
    end else begin
        b_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            b_address1_local = zext_ln16_50_fu_872_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            b_address1_local = zext_ln16_59_fu_815_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            b_address1_local = zext_ln16_55_fu_759_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            b_address1_local = zext_ln16_51_fu_710_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            b_address1_local = zext_ln16_60_fu_663_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            b_address1_local = zext_ln16_56_fu_613_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            b_address1_local = zext_ln16_52_fu_559_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            b_address1_local = zext_ln12_fu_486_p1;
        end else begin
            b_address1_local = 'bx;
        end
    end else begin
        b_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b_ce0_local = 1'b1;
    end else begin
        b_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        b_ce1_local = 1'b1;
    end else begin
        b_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_ce0_local = 1'b1;
    end else begin
        prod_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prod_we0_local = 1'b1;
    end else begin
        prod_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter2_stage0) & (ap_idle_pp0_0to1 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to2 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_address0 = a_address0_local;

assign a_address1 = a_address1_local;

assign a_ce0 = a_ce0_local;

assign a_ce1 = a_ce1_local;

assign add_ln10_1_fu_908_p2 = (indvar_flatten1_fu_114 + 8'd1);

assign add_ln10_fu_506_p2 = (i2_fu_118 + 5'd1);

assign add_ln16_12_fu_1190_p2 = (zext_ln16_43_fu_1187_p1 + zext_ln16_42_fu_1184_p1);

assign add_ln16_13_fu_1200_p2 = (zext_ln16_44_fu_1196_p1 + zext_ln16_41_fu_1181_p1);

assign add_ln16_14_fu_1216_p2 = (zext_ln16_45_fu_1213_p1 + zext_ln16_38_fu_1210_p1);

assign add_ln16_15_fu_867_p2 = (zext_ln16_49_reg_1474 + 6'd16);

assign add_ln16_16_fu_553_p2 = (zext_ln16_48_fu_550_p1 + 7'd48);

assign add_ln16_17_fu_564_p2 = ($signed(zext_ln16_48_fu_550_p1) + $signed(7'd80));

assign add_ln16_18_fu_607_p2 = (zext_ln16_47_fu_604_p1 + 8'd112);

assign add_ln16_19_fu_618_p2 = ($signed(zext_ln16_47_fu_604_p1) + $signed(8'd144));

assign add_ln16_20_fu_658_p2 = ($signed(zext_ln16_47_reg_1404) + $signed(8'd176));

assign add_ln16_21_fu_629_p2 = (tmp_reg_1359 + zext_ln16_47_fu_604_p1);

assign add_ln16_2_fu_1060_p2 = (zext_ln16_33_fu_1057_p1 + zext_ln16_32_fu_1054_p1);

assign add_ln16_5_fu_1098_p2 = (zext_ln16_36_fu_1095_p1 + zext_ln16_35_fu_1092_p1);

assign add_ln16_6_fu_1108_p2 = (zext_ln16_37_fu_1104_p1 + zext_ln16_34_fu_1089_p1);

assign add_ln16_9_fu_1159_p2 = (zext_ln16_40_fu_1156_p1 + zext_ln16_39_fu_1153_p1);

assign add_ln16_s_fu_973_p3 = {{xor_ln16_fu_968_p2}, {trunc_ln16_reg_1336}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1225 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln10_reg_1635 == 1'd0));
end

always @ (*) begin
    ap_condition_1237 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1242 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln10_reg_1635 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign b_address0 = b_address0_local;

assign b_address1 = b_address1_local;

assign b_ce0 = b_ce0_local;

assign b_ce1 = b_ce1_local;

assign empty_fu_520_p1 = i_fu_512_p3[3:0];

assign grp_fu_1227_p0 = grp_fu_1227_p00;

assign grp_fu_1227_p00 = reg_437;

assign grp_fu_1227_p1 = grp_fu_1227_p10;

assign grp_fu_1227_p10 = reg_432;

assign grp_fu_1227_p2 = grp_fu_1227_p20;

assign grp_fu_1227_p20 = mul_ln16_2_fu_893_p2;

assign grp_fu_1235_p0 = grp_fu_1235_p00;

assign grp_fu_1235_p00 = reg_441;

assign grp_fu_1235_p1 = grp_fu_1235_p10;

assign grp_fu_1235_p10 = reg_446;

assign grp_fu_1235_p2 = grp_fu_1235_p20;

assign grp_fu_1235_p20 = mul_ln16_4_fu_993_p2;

assign grp_fu_1243_p0 = grp_fu_1243_p00;

assign grp_fu_1243_p00 = reg_424;

assign grp_fu_1243_p1 = grp_fu_1243_p10;

assign grp_fu_1243_p10 = reg_428;

assign grp_fu_1243_p2 = grp_fu_1243_p20;

assign grp_fu_1243_p20 = mul_ln16_1_fu_1017_p2;

assign grp_fu_1252_p0 = grp_fu_1252_p00;

assign grp_fu_1252_p00 = b_load_7_reg_1444;

assign grp_fu_1252_p1 = grp_fu_1252_p10;

assign grp_fu_1252_p10 = reg_451;

assign grp_fu_1252_p2 = grp_fu_1252_p20;

assign grp_fu_1252_p20 = mul_ln16_6_fu_1041_p2;

assign grp_fu_1261_p0 = grp_fu_1261_p00;

assign grp_fu_1261_p00 = b_load_9_reg_1449;

assign grp_fu_1261_p1 = grp_fu_1261_p10;

assign grp_fu_1261_p10 = a_load_9_reg_1464;

assign grp_fu_1261_p2 = grp_fu_1261_p20;

assign grp_fu_1261_p20 = mul_ln16_8_fu_1076_p2;

assign grp_fu_1269_p0 = grp_fu_1269_p00;

assign grp_fu_1269_p00 = b_load_11_reg_1500;

assign grp_fu_1269_p1 = grp_fu_1269_p10;

assign grp_fu_1269_p10 = a_load_11_reg_1469;

assign grp_fu_1269_p2 = grp_fu_1269_p20;

assign grp_fu_1269_p20 = mul_ln16_10_fu_1123_p2;

assign grp_fu_1278_p0 = grp_fu_1278_p00;

assign grp_fu_1278_p00 = b_load_13_reg_1505;

assign grp_fu_1278_p1 = grp_fu_1278_p10;

assign grp_fu_1278_p10 = a_load_13_reg_1525;

assign grp_fu_1278_p2 = grp_fu_1278_p20;

assign grp_fu_1278_p20 = mul_ln16_12_fu_1143_p2;

assign grp_fu_1286_p0 = grp_fu_1286_p00;

assign grp_fu_1286_p00 = reg_456;

assign grp_fu_1286_p1 = grp_fu_1286_p10;

assign grp_fu_1286_p10 = a_load_15_reg_1530;

assign grp_fu_1286_p2 = grp_fu_1286_p20;

assign grp_fu_1286_p20 = mul_ln16_14_fu_1171_p2;

assign i_fu_512_p3 = ((icmp_ln124_reg_413[0:0] == 1'b1) ? add_ln10_fu_506_p2 : i2_fu_118);

assign icmp_ln10_fu_920_p2 = ((indvar_flatten1_fu_114 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln12_fu_914_p2 = ((j_fu_903_p2 == 5'd16) ? 1'b1 : 1'b0);

assign j_fu_903_p2 = (select_ln10_reg_1316 + 5'd1);

assign mul_ln16_10_fu_1123_p0 = mul_ln16_10_fu_1123_p00;

assign mul_ln16_10_fu_1123_p00 = b_load_10_reg_1620;

assign mul_ln16_10_fu_1123_p1 = mul_ln16_10_fu_1123_p10;

assign mul_ln16_10_fu_1123_p10 = a_load_10_reg_1654;

assign mul_ln16_12_fu_1143_p0 = mul_ln16_12_fu_1143_p00;

assign mul_ln16_12_fu_1143_p00 = b_load_12_reg_1625;

assign mul_ln16_12_fu_1143_p1 = mul_ln16_12_fu_1143_p10;

assign mul_ln16_12_fu_1143_p10 = a_load_12_reg_1689;

assign mul_ln16_14_fu_1171_p0 = mul_ln16_14_fu_1171_p00;

assign mul_ln16_14_fu_1171_p00 = b_load_14_reg_1674;

assign mul_ln16_14_fu_1171_p1 = mul_ln16_14_fu_1171_p10;

assign mul_ln16_14_fu_1171_p10 = a_load_14_reg_1694;

assign mul_ln16_1_fu_1017_p0 = mul_ln16_1_fu_1017_p00;

assign mul_ln16_1_fu_1017_p00 = reg_424;

assign mul_ln16_1_fu_1017_p1 = mul_ln16_1_fu_1017_p10;

assign mul_ln16_1_fu_1017_p10 = reg_432;

assign mul_ln16_2_fu_893_p0 = mul_ln16_2_fu_893_p00;

assign mul_ln16_2_fu_893_p00 = reg_437;

assign mul_ln16_2_fu_893_p1 = mul_ln16_2_fu_893_p10;

assign mul_ln16_2_fu_893_p10 = reg_446;

assign mul_ln16_4_fu_993_p0 = mul_ln16_4_fu_993_p00;

assign mul_ln16_4_fu_993_p00 = reg_456;

assign mul_ln16_4_fu_993_p1 = mul_ln16_4_fu_993_p10;

assign mul_ln16_4_fu_993_p10 = reg_428;

assign mul_ln16_6_fu_1041_p0 = mul_ln16_6_fu_1041_p00;

assign mul_ln16_6_fu_1041_p00 = reg_441;

assign mul_ln16_6_fu_1041_p1 = mul_ln16_6_fu_1041_p10;

assign mul_ln16_6_fu_1041_p10 = reg_446;

assign mul_ln16_8_fu_1076_p0 = mul_ln16_8_fu_1076_p00;

assign mul_ln16_8_fu_1076_p00 = b_load_8_reg_1580;

assign mul_ln16_8_fu_1076_p1 = mul_ln16_8_fu_1076_p10;

assign mul_ln16_8_fu_1076_p10 = reg_451;

assign prod_address0 = zext_ln16_65_fu_1206_p1;

assign prod_ce0 = prod_ce0_local;

assign prod_d0 = zext_ln16_46_fu_1222_p1;

assign prod_we0 = prod_we0_local;

assign select_ln10_fu_478_p3 = ((ap_phi_mux_icmp_ln124_phi_fu_416_p4[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_j3_load);

assign sext_ln16_1_fu_820_p1 = tmp_17_cast_reg_1490;

assign sext_ln16_2_fu_668_p1 = add_ln16_17_reg_1384;

assign sext_ln16_3_fu_877_p1 = tmp_16_cast_reg_1479;

assign sext_ln16_4_fu_980_p1 = $signed(add_ln16_s_fu_973_p3);

assign sext_ln16_fu_756_p1 = tmp_16_cast_reg_1479;

assign tmp_10_cast_fu_854_p1 = tmp_s_fu_847_p3;

assign tmp_10_fu_646_p3 = {{empty_reg_1341}, {4'd11}};

assign tmp_11_cast_fu_653_p1 = tmp_10_fu_646_p3;

assign tmp_11_fu_936_p3 = {{empty_reg_1341}, {4'd12}};

assign tmp_12_cast_fu_943_p1 = tmp_11_fu_936_p3;

assign tmp_12_fu_676_p3 = {{empty_reg_1341}, {4'd13}};

assign tmp_13_cast_fu_683_p1 = tmp_12_fu_676_p3;

assign tmp_13_fu_948_p3 = {{empty_reg_1341}, {4'd14}};

assign tmp_14_cast_fu_955_p1 = tmp_13_fu_948_p3;

assign tmp_14_fu_688_p3 = {{empty_reg_1341}, {4'd15}};

assign tmp_15_cast_fu_695_p1 = tmp_14_fu_688_p3;

assign tmp_16_cast_fu_703_p3 = {{1'd1}, {select_ln10_reg_1316}};

assign tmp_17_cast_fu_715_p3 = {{1'd1}, {zext_ln16_49_fu_700_p1}};

assign tmp_19_cast_fu_764_p3 = {{1'd1}, {zext_ln16_48_reg_1374}};

assign tmp_1_cast_fu_735_p1 = tmp_1_fu_728_p3;

assign tmp_1_fu_728_p3 = {{empty_reg_1341}, {4'd1}};

assign tmp_20_cast_fu_808_p3 = {{3'd5}, {select_ln10_reg_1316}};

assign tmp_2_cast_fu_747_p1 = tmp_2_fu_740_p3;

assign tmp_2_fu_740_p3 = {{empty_reg_1341}, {4'd2}};

assign tmp_3_cast_fu_545_p1 = tmp_3_fu_537_p3;

assign tmp_3_fu_537_p3 = {{empty_fu_520_p1}, {4'd3}};

assign tmp_4_cast_fu_787_p1 = tmp_4_fu_780_p3;

assign tmp_4_fu_780_p3 = {{empty_reg_1341}, {4'd4}};

assign tmp_5_cast_fu_587_p1 = tmp_5_fu_580_p3;

assign tmp_5_fu_580_p3 = {{empty_reg_1341}, {4'd5}};

assign tmp_6_cast_fu_799_p1 = tmp_6_fu_792_p3;

assign tmp_6_fu_792_p3 = {{empty_reg_1341}, {4'd6}};

assign tmp_7_cast_fu_599_p1 = tmp_7_fu_592_p3;

assign tmp_7_fu_592_p3 = {{empty_reg_1341}, {4'd7}};

assign tmp_8_cast_fu_842_p1 = tmp_8_fu_835_p3;

assign tmp_8_fu_835_p3 = {{empty_reg_1341}, {4'd8}};

assign tmp_9_cast_fu_641_p1 = tmp_9_fu_634_p3;

assign tmp_9_fu_634_p3 = {{empty_reg_1341}, {4'd9}};

assign tmp_cast_fu_532_p1 = tmp_fu_524_p3;

assign tmp_fu_524_p3 = {{empty_fu_520_p1}, {4'd0}};

assign tmp_s_fu_847_p3 = {{empty_reg_1341}, {4'd10}};

assign trunc_ln16_fu_499_p1 = select_ln10_fu_478_p3[3:0];

assign xor_ln16_fu_968_p2 = (bit_sel_reg_1331 ^ 1'd1);

assign zext_ln12_fu_486_p1 = select_ln10_fu_478_p3;

assign zext_ln16_32_fu_1054_p1 = grp_fu_1243_p3;

assign zext_ln16_33_fu_1057_p1 = add_ln16_1_reg_1679;

assign zext_ln16_34_fu_1089_p1 = add_ln16_2_reg_1729;

assign zext_ln16_35_fu_1092_p1 = add_ln16_3_reg_1709;

assign zext_ln16_36_fu_1095_p1 = grp_fu_1252_p3;

assign zext_ln16_37_fu_1104_p1 = add_ln16_5_fu_1098_p2;

assign zext_ln16_38_fu_1210_p1 = add_ln16_6_reg_1749;

assign zext_ln16_39_fu_1153_p1 = add_ln16_7_reg_1769;

assign zext_ln16_40_fu_1156_p1 = grp_fu_1269_p3;

assign zext_ln16_41_fu_1181_p1 = add_ln16_9_reg_1779;

assign zext_ln16_42_fu_1184_p1 = add_ln16_10_reg_1789;

assign zext_ln16_43_fu_1187_p1 = grp_fu_1286_p3;

assign zext_ln16_44_fu_1196_p1 = add_ln16_12_fu_1190_p2;

assign zext_ln16_45_fu_1213_p1 = add_ln16_13_reg_1794;

assign zext_ln16_46_fu_1222_p1 = add_ln16_14_fu_1216_p2;

assign zext_ln16_47_fu_604_p1 = select_ln10_reg_1316;

assign zext_ln16_48_fu_550_p1 = select_ln10_reg_1316;

assign zext_ln16_49_fu_700_p1 = select_ln10_reg_1316;

assign zext_ln16_50_fu_872_p1 = add_ln16_15_fu_867_p2;

assign zext_ln16_51_fu_710_p1 = $unsigned(tmp_16_cast_fu_703_p3);

assign zext_ln16_52_fu_559_p1 = add_ln16_16_fu_553_p2;

assign zext_ln16_53_fu_723_p1 = $unsigned(tmp_17_cast_fu_715_p3);

assign zext_ln16_54_fu_570_p1 = $unsigned(add_ln16_17_fu_564_p2);

assign zext_ln16_55_fu_759_p1 = $unsigned(sext_ln16_fu_756_p1);

assign zext_ln16_56_fu_613_p1 = add_ln16_18_fu_607_p2;

assign zext_ln16_57_fu_771_p1 = tmp_19_cast_fu_764_p3;

assign zext_ln16_58_fu_624_p1 = add_ln16_19_fu_618_p2;

assign zext_ln16_59_fu_815_p1 = tmp_20_cast_fu_808_p3;

assign zext_ln16_60_fu_663_p1 = add_ln16_20_fu_658_p2;

assign zext_ln16_61_fu_823_p1 = $unsigned(sext_ln16_1_fu_820_p1);

assign zext_ln16_62_fu_671_p1 = $unsigned(sext_ln16_2_fu_668_p1);

assign zext_ln16_63_fu_880_p1 = $unsigned(sext_ln16_3_fu_877_p1);

assign zext_ln16_64_fu_984_p1 = $unsigned(sext_ln16_4_fu_980_p1);

assign zext_ln16_65_fu_1206_p1 = add_ln16_21_reg_1419_pp0_iter1_reg;

always @ (posedge ap_clk) begin
    tmp_reg_1359[3:0] <= 4'b0000;
    zext_ln16_48_reg_1374[6:5] <= 2'b00;
    zext_ln16_47_reg_1404[7:5] <= 3'b000;
    zext_ln16_49_reg_1474[5] <= 1'b0;
    tmp_16_cast_reg_1479[5] <= 1'b1;
    tmp_17_cast_reg_1490[6:5] <= 2'b10;
end

endmodule //matrix_mult
